config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get ':id/buy' => 'items#buy'
    end
    collection do
      post ':id/pay' => 'items#pay'
    end
  end
  resources :brands, only: :index
  resources :categories, only: [:index ,:show]
  namespace :mypages do
    resources :identifications, only: [:new, :create]
    resources :logins, only: :index
    resources :logouts, only: :index
    resources :cards, only: [:index,:new,:create]

  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy]
  resources :signup, only: [:index]
  namespace :signup do
    resources :registrations, only: [:new, :create]
    resources :sms_confirmations, only: :index
    namespace :sms_confirmations do
      resources :sms, only: :index
    end
    resources :addresses, only: [:new, :create]
    resources :credit_cards, only: [:new, :create]
  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy,:card]
  resources :buys, only: :index
  resources :item_images, only: [:create, :destroy]
  resources :searches, only: [:index ,:create]
  resources :search_keywords, only: :index
end

app/controllers/mypages/cards_controller.rb
class Mypages::CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only:  [:index,:new]
  def index
  end

  def new
    @credits = CreditCard.all
  end

  def create
      Payjp.api_key = "#{ENV['PAYJP_PRIVATE_KEY']}"
      hensu = Payjp::Customer.create(
        description: 'test'
      )
      CreditCard.create(customer_id: hensu[:id],user_id: current_user.id,name: current_user.name)
      tano = current_user.credit_cards.last.customer_id
      token_name = params[:token_name]
      customer = Payjp::Customer.retrieve(tano)
      customer.cards.create(
        card: token_name
      )
      redirect_to  root_path
  end

  private
  def pay_params
    params.permit(:id)
  end

  private
  def set_category
    @category = Category.all
  end
end

app/controllers/mypages/identifications_controller.rb
class Mypages::IdentificationsController < ApplicationController
  before_action :authenticate_user!
  def new
  end

end

app/controllers/mypages/logins_controller.rb
class Mypages::LoginsController < ApplicationController

  def index

  end

end

app/controllers/mypages/logouts_controller.rb
class Mypages::LogoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only:  :index


  def index

  end
  private
  def set_category
    @category = Category.all
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only:  [:show,:edit]
  def show
  end

  def edit
  end

  private
  def set_category
    @category = Category.all
  end

end

app/helpers/mypages/identifications_helper.rb
module Mypages::IdentificationsHelper
end

app/helpers/mypages/logins_helper.rb
module Mypages::LoginsHelper
end

app/helpers/mypages/logouts_helper.rb
module Mypages::LogoutsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/cards/create.html.haml
支払い完了いたしました。

app/views/mypages/cards/index.html.haml
= render "shered/header"
.pankuzu
  - breadcrumb :mypages_cards
  = breadcrumbs separator: "<text class='fas fa-chevron-right pankuzu__arrow-icon'></text>"
.mypage
  - button_main_number = 18
  = render "/mypages/shered/header",button_main_number:button_main_number
  .mypage__main
    .mypage_card
      .mypage_card__title
        支払い方法
    .mypage_card__content
      .mypage_card__content__name
        クレジットカード一覧
      .mypage_card__content__add-button
        = link_to new_mypages_card_path do
          %span.mypage_card__content__add-button--icon
            .fas.fa-credit-card
          %span.mypage_card__content__add-button--text
            クレジットカードを追加する
    .mypage_card__payment
      .mypage_card__payment__box
        .mypage_card__payment__box__button
          =link_to root_path do
            %span.mypage_card__payment__box__button--text
              支払い方法について
            %i.mypage_card__payment__box__button--icon
              .fas.fa-chevron-right



= render "shered/fotter"

app/views/mypages/cards/new.html.haml
= render "shered/header"
.pankuzu
  - breadcrumb :new_mypages_card
  = breadcrumbs separator: "<text class='fas fa-chevron-right pankuzu__arrow-icon'></text>"
.mypage
  - button_main_number = 18
  = render "/mypages/shered/header",button_main_number:button_main_number
  .mypage__main
    .card_new
      .card_new__title
        クレジットカード情報入力
      .card_new__content
        .card_new__content__box
          .card_new__content__box__card_no
            .card_new__content__box__card_no__upper
              %span.card_new__content__box__card_no__upper--title
                カード番号
              %span.card_new__content__box__card_no__upper--mark
                必須
            %input.card_new__content__box__card_no--textbox{type: "text",placeholder:"半角数字のみ"}
            .card_new__content__box__card_no__cardlist
              =image_tag("/mypage_images/card_new/visa.svg/",class: "card_new__content__box__card_no__cardlist--image")
              =image_tag("/mypage_images/card_new/master-card.svg/",class: "card_new__content__box__card_no__cardlist--image")
              =image_tag("/mypage_images/card_new/saison-card.svg/",class: "card_new__content__box__card_no__cardlist--image")
              =image_tag("/mypage_images/card_new/jcb.svg/",class: "card_new__content__box__card_no__cardlist--image")
              =image_tag("/mypage_images/card_new/american_express.svg/",class: "card_new__content__box__card_no__cardlist--image")
              =image_tag("/mypage_images/card_new/dinersclub.svg/",class: "card_new__content__box__card_no__cardlist--image")
              =image_tag("/mypage_images/card_new/discover.svg/",class: "card_new__content__box__card_no__cardlist--image")
          .card_new__content__box__card_no
            .card_new__content__box__card_no__upper
              %span.card_new__content__box__card_no__upper--title
                有効期限
              %span.card_new__content__box__card_no__upper--mark
                必須

            .card_new__content__box__day
              .card_new__content__box__day__box
                %input.card_new__content__box__day__box--text{type: "text",placeholder:"---"}

              .card_new__content__box__day--right-text
                月
            .card_new__content__box__day
              .card_new__content__box__day__box
                %input.card_new__content__box__day__box--text{type: "text",placeholder:"---"}

              .card_new__content__box__day--right-text
                年


          .card_new__content__box__card_no
            .card_new__content__box__card_no__upper
              %span.card_new__content__box__card_no__upper--title
                セキュリティコード
              %span.card_new__content__box__card_no__upper--mark
                必須
            %input.card_new__content__box__card_no--textbox{type: "text",placeholder:"カード背面4桁もしくは3桁の番号"}
            .card_new__content__box__discription
              .fas.fa-question-circle.card_new__content__box__discription--icon
              .card_new__content__box__discription--text
                カード裏面の番号とは？
          - if @credits.empty? or current_user.credit_cards.empty?
            .card_new__content__box__red-button
              = form_tag(action: :create, method: :post) do
                %script.payjp-button{"data-key" => "#{ENV['PAYJP_PUBLIC_KEY']}", :src => "https://checkout.pay.jp", :type => "text/javascript", "data-token-name" => "token_name"}

          - elsif current_user.credit_cards.first.customer_id = true
            .card_new__content__box__false-button
              既に登録されています

          - else
            .card_new__content__box__false-button
              予期しないエラーが発生しました。

= render "shered/fotter"

app/views/mypages/cards/pay.html.haml
コントローラのpathの指定に問題があります