config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get ':id/buy' => 'items#buy'
    end
    collection do
      post ':id/pay' => 'items#pay'
    end
  end
  resources :brands, only: :index
  resources :categories, only: [:index ,:show]
  namespace :mypages do
    resources :identifications, only: [:new, :create]
    resources :logins, only: :index
    resources :logouts, only: :index
    resources :cards, only: [:index,:new,:create]

  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy]
  resources :signup, only: [:index]
  namespace :signup do
    resources :registrations, only: [:new, :create]
    resources :sms_confirmations, only: :index
    namespace :sms_confirmations do
      resources :sms, only: :index
    end
    resources :addresses, only: [:new, :create]
    resources :credit_cards, only: [:new, :create]
  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy,:card]
  resources :buys, only: :index
  resources :item_images, only: [:create, :destroy]
  resources :searches, only: [:index ,:create]
  resources :search_keywords, only: :index
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :BrandItems
  has_many :items, through: :BrandItems
end

app/models/brand_item.rb
class BrandItem < ApplicationRecord
  belongs_to :item
  belongs_to :brand
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :CategoryItems
  has_many :items, through: :CategoryItems
end

app/models/category_item.rb
class CategoryItem < ApplicationRecord
  belongs_to :category
  belongs_to :item
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :items
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :item
  belongs_to :evaluator
end

app/models/evaluator.rb
class Evaluator < ApplicationRecord
  belongs_to :user
  belongs_to :evaluation
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  has_many :Category_items, dependent: :destroy
  has_many :categories, through: :Category_items, dependent: :destroy
  has_many :BrandItems
  has_many :brands, through: :BrandItems, dependent: :destroy
  has_many :item_image_items
  has_many :item_images, through: :item_image_items, dependent: :destroy
  belongs_to :condition
  belongs_to :shipping_burden
  belongs_to :shipping_style
  belongs_to :date_of_shipment
  has_many :credit
  has_many :buyer
  has_many :item_size_items, dependent: :destroy
  has_many :item_sizes, through: :item_size_items
  belongs_to :status
  has_many :messages, dependent: :destroy


  accepts_nested_attributes_for :item_images

  validates_presence_of :name,:description, :user_id, :condition_id, :shipping_burden_id, :shipping_style_id, :prefecture_id, :date_of_shipment_id, :price, :status_id, :category_ids, :item_size_ids

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :prefecture

  accepts_nested_attributes_for :item_images, allow_destroy: true
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  has_many :item_image_items
  has_many :items, through: :item_image_items

  validates_presence_of :image
  mount_uploader :image, ImageUploader
end

app/models/item_size.rb
class ItemSize < ApplicationRecord
  has_many :item_size_items
  has_many :items, through: :item_size_items
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,omniauth_providers: [:facebook, :google_oauth2]

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.create(
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return user
  end

  validates :email, presence: true

  has_many :items, dependent: :destroy
  has_many :credits, dependent: :destroy
  has_many :ContactInformations, dependent: :destroy
  has_many :informations
  has_many :points, dependent: :destroy
  has_many :evaluations
  has_many :likes
  has_many :messages
  has_many :buyers
  has_many :credit_cards

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_category, only:  [:index]

  def index
    @view_items = params[:keyword].empty? ? []  : Item.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)

    @search = Item.ransack(:q)
    @items = @search.result(distinct: true).includes(:item_images)
  end

  def create
      @search = Item.ransack(search_params)
      @items = @search.result(distinct: true).includes(:item_images)
      respond_to do |format|
        format.json
      end
  end

  private
  def search_params
    params.require(:q).permit(:name_cont,:categories_ancestry_eq,:categories_id_in,:brands_name_eq,:item_sizes_id_in,:price_gteq,:price_lteq,:shipping_burden_id_in,:status_id_in,:s)

  end

  def set_category
    @category = Category.all
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/searches/index.html.haml
= render "shered/header"
.search
  .search__main
    .search__search_bar
      = search_form_for @search, url: searches_path,method: "POST" do |f|
        .search__search_bar--sort
          = f.select :s ,{"並び替え": "","価格の安い順": "price asc", "価格の高い順": "price desc","出品の古い順": "created_at asc","出品の新しい順": "created_at desc"},{},{class: "search__sort search__search_bar--sort-input",id: "search__sort"}

          .fas.fa-chevron-down.search__search_bar--sort-allow_icon
        .search__search_bar--detailed_search
          .search__search_bar--detailed_search-title
            詳細検索
          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .fas.fa-plus.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                キーワードを追加する
            .search__search_bar--detailed_search-input
              = f.search_field :name_cont , class:"search__search_bar--detailed_search-input-box",autocomplete: "off"
          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .fas.fa-list.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                カテゴリーを選択する
            .search__search_bar--detailed_search-input
              .fas.fa-chevron-down.search__search_bar--detailed_search-input-arrow_icon
            .search__search_bar--detailed_search-input.search__search_bar--category.search__search_bar--category-parents
              = f.collection_select :categories_id ,Category.where(ancestry: nil),:id,:name,{include_blank: "すべて"},{class: "search__search_bar--detailed_search-input-box",id:"search__category-parent", type: "text",autocomplete: "off" }
              .fas.fa-chevron-down.search__search_bar--detailed_search-input-allow-icon
          - Category.where(ancestry: nil).each do |parent|
            .search__search_bar--detailed_search-input.search__search_bar--detailed_search-input-child.search__search_bar--category-child{ class:"search__search_bar--category-#{parent.id}"}
              = f.collection_select :categories_ancestry_eq ,Category.where(ancestry: parent.id),:id,:name,{multiple: true,include_blank: "すべて"},{class: "search__search_bar--detailed_search-input-box-child search__search_bar--detailed_search-input-box",id:"search__category-child-#{parent.id}", type: "text",autocomplete: "off" }
              .fas.fa-chevron-down.search__search_bar--detailed_search-input-allow-icon-child
              %br
          .search__search_bar--detailed_search-input-check-boxs
            - Category.where("id > ?",159).find_each do |grandchild|
              .search__search_bar--detailed_search-input.search__search_bar--category-grandchild{category_grandchild:grandchild.id, class:"search__search_bar--category-#{grandchild.ancestry}" }
                .search__search_bar--detailed_search-input-check-box
                  .search__search_bar--detailed_search-input-check-box-box
                    = f.check_box :categories_id_in_any , { multiple: true },grandchild.id,name:grandchild.name,class: "search__search_bar--detailed_search-input-check-box", type: "text",value: grandchild.id
                  .search__search_bar--detailed_search-input-check-box-text
                    = grandchild.name

          %br
          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .fas.fa-tag.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                ブランド名から探す
            .search__search_bar--detailed_search-input
              = f.search_field :brands_name_eq , class:"search__search_bar--detailed_search-input-box search__brand-input",autocomplete: "off"
              .search__search_bar--detailed_search-input-suggest
          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .far.fa-square.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                サイズを指定する
            .search__search_bar--detailed_search-input
              = f.collection_select :item_sizes_id ,ItemSize.where(parents: nil),:id,:name,{include_blank: "すべて"},{class: "search__search_bar--detailed_search-input-box",id: "search__item_size",autocomplete: "off" }
              .fas.fa-chevron-down.search__search_bar--detailed_search-input-allow-icon
              %br
              .search__search_bar--detailed_search-input-check-boxs
                - ItemSize.where("id > ?", 15 ).each do |item_sizes_child|
                  .search__search_bar--detailed_search-input-item_size-box.search__hide{class: "search__item_sizes_#{item_sizes_child.parents}"}
                    .search__search_bar--detailed_search-input-check-box
                      .search__search_bar--detailed_search-input-check-box-box
                        = f.check_box :item_sizes_id_in_any , { multiple: true },name:item_sizes_child.name,class: "search__search_bar--detailed_search-input ", type: "text",value: item_sizes_child.id
                      .search__search_bar--detailed_search-input-check-box-text
                        = item_sizes_child.name
          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .fas.fa-funnel-dollar.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                価格
              %br
            .search__search_bar--detailed_search-input
              = f.select :price, {"選択してください": "---","300 ~ 1000": "300 ~ 1000","1000 ~ 5000": "1000 ~ 5000","5000 ~ 10000": "5000 ~ 10000","10000 ~ 30000": "10000 ~ 30000", "30000 ~ 50000": "30000 ~ 50000","50000 ~": "50000 ~"},{},{class: "search__search_bar--detailed_search-input-price search__search_bar--detailed_search-input-box",id: "search__price-input",autocomplete: "off" }

              .fas.fa-chevron-down.search__search_bar--detailed_search-input-allow-icon
            .search__search_bar--detailed_search-input-range-boxs
              = f.text_field :price_gteq, class: "search__search_bar--detailed_search-input-range-box",id: "search__price-input-low",placeholder: "¥ Min",autocomplete: "off"
              .search__search_bar--detailed_search-input-range-icon ~
              = f.text_field :price_lteq, class: "search__search_bar--detailed_search-input-range-box",id: "search__price-input-high",placeholder: "¥ Max",autocomplete: "off"

          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .fas.fa-star.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                商品の状態

            .search__search_bar--detailed_search-input-check-boxs
              .search__search_bar--detailed_search-input-check-box
                .search__search_bar--detailed_search-input-check-box-box
                  = f.check_box :condition_id,{id:"search__check-box-all-condition"},checked_value: nil,unchecked_value: nil
                .search__search_bar--detailed_search-input-check-box-text
                  すべて
              - Condition.all.each do |condition|
                .search__search_bar--detailed_search-input-check-box
                  .search__search_bar--detailed_search-input-check-box-box
                    =  f.check_box :condition_id_in_any,{},checked_value: condition.id,unchecked_value: nil
                  .search__search_bar--detailed_search-input-check-box-text
                    = condition.name

          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .fas.fa-truck.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                送料の負担
            .search__search_bar--detailed_search-input-check-boxs
              .search__search_bar--detailed_search-input-check-box
                .search__search_bar--detailed_search-input-check-box-box
                  = f.check_box :shipping_burden_id ,{id:"search__check-box-all-shipping_burden"},checked_value: nil,unchecked_value: nil
                .search__search_bar--detailed_search-input-check-box-text
                  すべて
              - ShippingBurden.all.each do |shipping_burden|
                .search__search_bar--detailed_search-input-check-box
                  .search__search_bar--detailed_search-input-check-box-box
                    = f.check_box :shipping_burden_id_in_any ,{},checked_value: shipping_burden.id,unchecked_value: nil
                  .search__search_bar--detailed_search-input-check-box-text
                    = shipping_burden.name

          .search__search_bar--detailed_search-box
            .search__search_bar--detailed_search-sub-title
              .fas.fa-shopping-cart.search__search_bar--detailed_search-sub-title-icon
              .search__sub-title
                販売状況
            .search__search_bar--detailed_search-input-check-boxs
              .search__search_bar--detailed_search-input-check-box
                .search__search_bar--detailed_search-input-check-box-box
                  = f.check_box :status_id,{id:"search__check-box-all-status"},checked_value: nil,unchecked_value: nil
                .search__search_bar--detailed_search-input-check-box-text
                  すべて
              - Status.all.each do |status|
                .search__search_bar--detailed_search-input-check-box
                  .search__search_bar--detailed_search-input-check-box-box
                    = f.check_box :status_id_in_any,{},checked_value: status.id,unchecked_value: nil
                  .search__search_bar--detailed_search-input-check-box-text
                    = status.name
            .search__check-box-space
          .search__form-buttons
            =  button_tag type: 'button', class: "search__form-clear" do
              クリア
            = f.submit '検索', class: "search__submit",id:"search__submit"

    .search__result
      - if @view_items.empty?
        .search__result--title
          検索結果 0件
        .search__result-description
          該当する商品が見つかりません。商品は毎日増えていますので、これからの出品に期待してください。
      - else
        .search__result--title
          検索結果 1-
          = @view_items.length
          件

      .search__result--boxs
        - @view_items.each do |item|
          = link_to  item_path(item) do
            .search__result--box
              .search__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
              .search__body
                .search__name
                  = item.name
                  .search__name_linear
                .search__price_and_like
                  .search__prices
                    .search__price
                      ¥ #{number_with_delimiter(item.price)}
                    .search__tax
                      (税込)
                  .search__like
                    .far.fa-heart.search__good_icon
                    .search__like_num
                      12

= render "shered/fotter"