config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get ':id/buy' => 'items#buy'
    end
    collection do
      post ':id/pay' => 'items#pay'
    end
  end
  resources :brands, only: :index
  resources :categories, only: [:index ,:show]
  namespace :mypages do
    resources :identifications, only: [:new, :create]
    resources :logins, only: :index
    resources :logouts, only: :index
    resources :cards, only: [:index,:new,:create]

  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy]
  resources :signup, only: [:index]
  namespace :signup do
    resources :registrations, only: [:new, :create]
    resources :sms_confirmations, only: :index
    namespace :sms_confirmations do
      resources :sms, only: :index
    end
    resources :addresses, only: [:new, :create]
    resources :credit_cards, only: [:new, :create]
  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy,:card]
  resources :buys, only: :index
  resources :item_images, only: [:create, :destroy]
  resources :searches, only: [:index ,:create]
  resources :search_keywords, only: :index
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  has_many :Category_items, dependent: :destroy
  has_many :categories, through: :Category_items, dependent: :destroy
  has_many :BrandItems
  has_many :brands, through: :BrandItems, dependent: :destroy
  has_many :item_image_items
  has_many :item_images, through: :item_image_items, dependent: :destroy
  belongs_to :condition
  belongs_to :shipping_burden
  belongs_to :shipping_style
  belongs_to :date_of_shipment
  has_many :credit
  has_many :buyer
  has_many :item_size_items, dependent: :destroy
  has_many :item_sizes, through: :item_size_items
  belongs_to :status
  has_many :messages, dependent: :destroy


  accepts_nested_attributes_for :item_images

  validates_presence_of :name,:description, :user_id, :condition_id, :shipping_burden_id, :shipping_style_id, :prefecture_id, :date_of_shipment_id, :price, :status_id, :category_ids, :item_size_ids

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :prefecture

  accepts_nested_attributes_for :item_images, allow_destroy: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!,only: [:new,:create,:buy,:pay]
  before_action :set_category, only: [:index, :show]

  def index

    @category_women = Category.find(1)
    @items_category_women = @category_women.items.order("created_at DESC").limit(4)

    @category_men = Category.find(2)
    @items_category_men = @category_men.items.order("created_at DESC").limit(4)

    @category_baby = Category.find(3)
    @items_category_baby = @category_baby.items.order("created_at DESC").limit(4)

    @category_cosmetic = Category.find(7)
    @items_category_cosmetic = @category_cosmetic.items.order("created_at DESC").limit(4)

    @brand_chanel = Brand.find(4116)
    @items_brand_chanel = @brand_chanel.items.order("created_at DESC").limit(4)

    @brand_louis_vuitton = Brand.find(4117)
    @items_brand_louis_vuitton = @brand_louis_vuitton.items.order("created_at DESC").limit(4)

    @brand_supreme = Brand.find(4118)
    @items_brand_supreme = @brand_supreme.items.order("created_at DESC").limit(4)

    @brand_nike = Brand.find(4119)
    @items_brand_nike = @brand_nike.items.order("created_at DESC").limit(4)
  end

  def new
    @item = Item.new
    @item.item_images.build
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update

    @item = Item.find(params[:id])
    if @item.user_id == current_user.id
      @item.update_attributes(item_params)
    end
    redirect_to root_path

  end

  def show
    @item = Item.find(params[:id])
    @item_name = Item.select("name")
    @item_price = Item.select("price")
    @items1 = Item.all.order("RAND(1)").limit(4)
    @items2 = Item.all.order("RAND(2)").limit(4)
  end

  def destroy
    item = Item.find(params[:id])
    if item.user_id == current_user.id
      item.destroy
      redirect_to root_path
    end
  end

  def buy
    @item = Item.find(params[:id])
    @credits = CreditCard.all
  end

  def pay
    Payjp.api_key = "#{ENV['PAYJP_PRIVATE_KEY']}"
    customer_id = current_user.credit_cards.last.customer_id
    price = params[:item_price]

    Payjp::Charge.create(
    amount: price,
    currency: 'jpy',
    customer: customer_id
    )
    item_id = params[:item_id]
    @item = Item.find(item_id)
    @item.status_id = 4
    @item.save

    redirect_to  root_path
  end

  private
  def item_params
    params.require(:item).permit(:status_id ,:category_ids, :item_size_ids, :brand_ids ,:name,:description,:condition_id,:shipping_burden_id, :shipping_style_id ,:prefecture_id,:date_of_shipment_id ,:price,item_images_attributes: [:id ,:image,:_destroy] ).merge(user_id: current_user.id)
  end

  def set_category
    @category = Category.all
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/buy.html.haml
.buy__wrapper
  .buy__header
    = link_to root_path do
      = image_tag("/top_images/mercari_color.svg", class: "mercari_color_icon" )

  .buy
    .buy__title
      購入を確定しますか？
    %hr.buy__line
    .buy__content
      .buy__content--inner
        = image_tag(@item.item_images.first.image.url,class: "buy__content__image")
      %p.buy__item-name
        #{@item.name}
      .buy__price--box
        %p.buy__price
          ¥ #{number_with_delimiter(@item.price)}
          %span.buy__shipping-fee
            #{@item.shipping_style.name}
      .buy__point--box
        %p.buy__point
          ポイントはありません
      .buy__payment-box
        .buy__payment-box__text
          支払い金額
        .buy__payment-box__price
          ¥ #{number_with_delimiter(@item.price)}

      - if @credits.empty? or current_user.credit_cards.empty?
        %p.buy__has-error-text
          クレジットカードの入力を完了してください。
        = button_tag("購入する",class:"buy__buy-botton-false")
      - elsif current_user.credit_cards.first.customer_id = true
        = form_tag(action:"pay", method: "post",item_id: @item.id,item_price: @item.price) do
          = button_tag("購入する",class:"buy__buy-botton")
      - else
        予期せぬエラーが発生しました
    %hr.buy__line
    .buy__content2
      .buy__content2__address
        .buy__content2__address__top
          配送先
        %address.buy__content2__address__center
          〒563-0058
        .buy__content2__address__button
    %hr.buy__line
    .buy__content3
      .buy__content3__payment
        %h3.buy__content3__payment__top
          支払い方法
        %address.buy__content3__payment__center
          ・クレジット払い
        .buy__content3__payment__button
          =link_to do
            %span.buy__content3__payment__button--text
              変更する
            %i.buy__content3__payment__button--icon
              .fas.fa-chevron-right





  = render "shered/item_fotter"

app/views/items/index.html.haml
= render "shered/header"

.top-main
  .slider
    .slide
      .first_slide

    .slide
      .second_slide
        .second_slide__sub_box
          .second_slide__phone_hand_image
            =image_tag("/top_images/main_content_pc.png")
          .text_button_area
            .second_slide__main_text
              スマホでかんたん
              %br フリマアプリ
            .second_slide__sub_text
              メルカリはスマホカメラからすぐに出品できる
              %br 購入時も安心な独自システムのアプリです。
            .second_slide__icons
              = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
                = image_tag('/top_images/app-store.svg', class: "second_slide__icons--app_store_icon")
              = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" do
                = image_tag('/top_images/google-play.svg', class: "second_slide__icons--google_play_icon")
    .slide
      .third__slide

  .top-products
    .pickup
      .pickup__title
        ピックアップカテゴリー
      .pickup__subtitle
        レディース 新着アイテム
      .pickup__products
        - @items_category_women.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else

              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"

  .top-products
    .pickup
      .pickup__subtitle
        メンズ 新着アイテム
      .pickup__products
        - @items_category_men.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"


  .top-products
    .pickup
      .pickup__subtitle
        ベビー・キッズ 新着アイテム
      .pickup__products
        - @items_category_baby.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"

  .top-products
    .pickup
      .pickup__subtitle
        コスメ・香水・美容 新着アイテム
      .pickup__products
        - @items_category_cosmetic.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"

  .top-products
    .pickup
      .pickup__title
        ピックアップブランド
      .pickup__subtitle
        シャネル 新着アイテム
      .pickup__products
        - @items_brand_chanel.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"

  .top-products
    .pickup
      .pickup__subtitle
        ルイ ヴィトン 新着アイテム
      .pickup__products
        - @items_brand_louis_vuitton.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"

  .top-products
    .pickup
      .pickup__subtitle
        シュプリーム 新着アイテム
      .pickup__products
        - @items_brand_supreme.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"

  .top-products
    .pickup
      .pickup__subtitle
        ナイキ 新着アイテム
      .pickup__products
        - @items_brand_nike.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12

      .pickup__show-all
        = link_to "すべての商品を見る", categories_path,class: "show-all__button"

= render "shered/fotter"

app/views/items/show.html.haml
= render "shered/header"
.pankuzu
  - breadcrumb :items, @item
  = breadcrumbs separator: "<text class='fas fa-chevron-right pankuzu__arrow-icon'></text>"
.wapper
  .tops_show
    .tops_show__main
      %h1.tops_show__main--header
        = @item.name
      .tops_show__main--top
        .tops_show__main--image
          - if @item.status_id == 4
            .tops_show__main--image__sold-out-badge
            .tops_show__main--image--text
              SOLD
          - else
          = image_tag(@item.item_images.first.image.url, class: "tops_show__main--left")
          .tops_show__main--right
            - @item.item_images.each do|itemimage|
              = image_tag(itemimage.image.url, class: "tops_show__main--details")
        %table.tops_show__main--information
          .tops_show__main--exhibitor
            %th.tops_show__main--exhibitor-left
              出品者
            %td.tops_show__main--exhibitor-right
              =link_to "#{@item.user.name}","",class: "exhibitor__right--name"
              .expression
                .fas.fa-laugh.smail
                %span 373
                .fas.fa-meh.usually
                %span 11
                .fas.fa-frown.sad
                %span 0
          %tr.tops_show__main--category
            %th.tops_show__main--category-left
              カテゴリー
            %td.tops_show__main--category-right
              = link_to "#{@item.categories.first.name}","",class: "tops_show__main--category-first"
              %br
              = link_to "",class: "tops_show__main--category-second" do
                %i.fas.fa-chevron-right
              %br
              = link_to "",class: "tops_show__main--category-third" do
                %i.fas.fa-chevron-right
          %tr.tops_show__main--bland
            %th.tops_show__main--bland-left ブランド
            %td.tops_show__main--bland-right
              - unless @item.brands.empty?
                = link_to "#{@item.brands.first.name}","",class: "tops_show__main--bland-right-name"

          %tr.tops_show__main--product-status
            %th.tops_show__main--product-status-left 商品の状態
            %td.tops_show__main--product-status-right
              = @item.condition.name
          %tr.tops_show__main--delivery-fee
            %th.tops_show__main--delivery-fee-left 配送料の不安
            %td.tops_show__main--delivery-fee-right
              = @item.shipping_burden.name
          %tr.tops_show__main--delivery-method
            %th.tops_show__main--delivery-method-left 配送の方法
            %td.tops_show__main--delivery-method-right
              = @item.shipping_style.name
          %tr.tops_show__main--delivery-source-area
            %th.tops_show__main--delivery-source-area-left 配送元地域
            %td.tops_show__main--delivery-source-area-right
              = link_to "#{@item.prefecture.name}","",class: "prefecture"
          %tr.tops_show__main--date-of-shipment
            %th.tops_show__main--date-of-shipment-left 発送日の目安
            %td.tops_show__main--date-of-shipment-right
              = @item.date_of_shipment.name
      .tops_show__main--money
        %span.tops_show__main--price
          ¥
          = number_with_delimiter(@item.price)
        %span.tops_show__main--tax （税込）
        %span.tops_show__main--fee 送料込み
      - if user_signed_in? && current_user.id == @item.user_id
        = link_to "削除","/items/#{@item.id}",method: "DELETE",class: "tops_show__main--purchase"
        = link_to "編集",edit_item_path(@item),class: "tops_show__main--purchase"
      - else
        -if @item.status_id == 4
          .tops_show__main--not-purchase
            売り切れました
        -else
          .tops_show__main--purchase
            = link_to "購入画面に進む","/items/#{@item.id}/buy",class: "tops_show__main--purchase"

      .tops_show__main--text
        .tops_show__main--description
          = @item.description

        .tops_show__main--containre
          .tops_show__main--containre-left
            .tops_show__main--containre-left-like
              %i.far.fa-heart
              =link_to "いいね！1","",class: "tops_show__main--good"
            .tops_show__main--containre-left-warning
              %i.far.fa-flag
              =link_to "不適切な商品の報告","https://www.mercari.com/jp/report/m85240041031/",class: "tops_show__main--report"
          .tops_show__main--containre-right
            = link_to "https://www.mercari.com/jp/safe/description/",class: "tops_show__main--containre-right-lock" do
              %i.fas.fa-lock
              あんしん・あんぜんへの取り組み

    .tops_show__message
      .tops_show__message--coteiner
        .tops_show__message--comment
          .tops_show__message--item
            .tops_show__message--grafic
              .tops_show__message--messagebody-main
                = link_to mypage_path do
                  = image_tag("/top_images/mercari_icon.png",class: "tops_show__message--grafic-image")
                .tops_show__message--messagebody-a
                  %figcaption.bold ❁ ぴょんぴょん ❁
                  .tops_show__message--messageboby
                    .tops_show__message--messageboby-text
                      .tops_show__message--messageboby-text-comment
                        .tops_show__message--messageboby-text-comment2
                          コメント失礼します(＞＜)購入希望ですが、3400円はキツイでしょうか？(＞＜)
                        .tops_show__message--messageboby-text-clock
                          %i.far.fa-clock
                            １日前
                          %i.far.fa-flag
              %form.tops_show__message--form
                %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
                %textarea
                .tops_show__message--button
                  %span コメントする

    %ul.tops_show__next
      %li.tops_show__next--left
        = link_to "",class: "tops_show__next--left-side" do
          %i.fas.fa-chevron-left
          NYヤンキースユニフォーム
      %li.tops_show__next--right
        = link_to "",class: "tops_show__next--right-side" do
          LAドジャースユニフォーム
          %i.fas.fa-chevron-right

    .tops_show__media-box
      %ul.tops_show__media-box--social
        .tops_show__media-box--icon
          = link_to "https://www.facebook.com/", class: "tops_show__media-box--facebook" do
            %i.fab.fa-facebook
          = link_to "https://twitter.com/", class: "tops_show__media-box--twiter" do
            %i.fab.fa-twitter
          = link_to "https://www.pinterest.jp/", class: "tops_show__media-box--pinterest" do
            %i.fab.fa-pinterest

.top-main--exhibitor
  .top-products--exhibitor
    .pickup
      .pickup__title
        =link_to "#{@item.user.name}さんのその他の商品","",class: "pickup__subtitle--exhibitor"
      .pickup__products
        - @items1.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else
              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12

      .pickup__products
        - @items2.each do |item|
          .product
            = link_to item_url(id: item.id) do
              .product__image
                = image_tag(item.item_images.first.image.url, class: "test_image")
                - if item.status_id == 4
                  .product__image__sold-out-badge
                  .product__image--text
                    SOLD
                - else

              .product__body
                .product__name
                  = item.name
                  .product__name_linear
                .product__price_and_like
                  .product__prices
                    .product__price
                      ¥ #{number_with_delimiter(item.price)}
                    .product__tax
                      (税込)
                  .product__like
                    .far.fa-heart.product__good_icon
                    .product__like_num
                      12
= render "shered/fotter"