config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get ':id/buy' => 'items#buy'
    end
    collection do
      post ':id/pay' => 'items#pay'
    end
  end
  resources :brands, only: :index
  resources :categories, only: [:index ,:show]
  namespace :mypages do
    resources :identifications, only: [:new, :create]
    resources :logins, only: :index
    resources :logouts, only: :index
    resources :cards, only: [:index,:new,:create]

  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy]
  resources :signup, only: [:index]
  namespace :signup do
    resources :registrations, only: [:new, :create]
    resources :sms_confirmations, only: :index
    namespace :sms_confirmations do
      resources :sms, only: :index
    end
    resources :addresses, only: [:new, :create]
    resources :credit_cards, only: [:new, :create]
  end
  resources :mypages, only: [:new, :create, :edit, :update, :show ,:destroy,:card]
  resources :buys, only: :index
  resources :item_images, only: [:create, :destroy]
  resources :searches, only: [:index ,:create]
  resources :search_keywords, only: :index
end

app/controllers/mypages/cards_controller.rb
class Mypages::CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only:  [:index,:new]
  def index
  end

  def new
    @credits = CreditCard.all
  end

  def create
      Payjp.api_key = "#{ENV['PAYJP_PRIVATE_KEY']}"
      hensu = Payjp::Customer.create(
        description: 'test'
      )
      CreditCard.create(customer_id: hensu[:id],user_id: current_user.id,name: current_user.name)
      tano = current_user.credit_cards.last.customer_id
      token_name = params[:token_name]
      customer = Payjp::Customer.retrieve(tano)
      customer.cards.create(
        card: token_name
      )
      redirect_to  root_path
  end

  private
  def pay_params
    params.permit(:id)
  end

  private
  def set_category
    @category = Category.all
  end
end

app/controllers/mypages/identifications_controller.rb
class Mypages::IdentificationsController < ApplicationController
  before_action :authenticate_user!
  def new
  end

end

app/controllers/mypages/logins_controller.rb
class Mypages::LoginsController < ApplicationController

  def index

  end

end

app/controllers/mypages/logouts_controller.rb
class Mypages::LogoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only:  :index


  def index

  end
  private
  def set_category
    @category = Category.all
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only:  [:show,:edit]
  def show
  end

  def edit
  end

  private
  def set_category
    @category = Category.all
  end

end

app/helpers/mypages/identifications_helper.rb
module Mypages::IdentificationsHelper
end

app/helpers/mypages/logins_helper.rb
module Mypages::LoginsHelper
end

app/helpers/mypages/logouts_helper.rb
module Mypages::LogoutsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/logins/index.html.haml
.login
  .login__wrapper
    .login__header
      = link_to root_path do
        = image_tag("/top_images/mercari_color.svg", class: "mercari_calor_icon" )

  .login__main
    .login__signup--link
      .login__signup--link-description
        アカウントをお持ちでない方はこちら
      = link_to signup_index_path do
        .login__signup--link-button
          新規会員登録
    .login__form
      = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
        .login__form--facebook
          .login__form--facebook-button
            .fab.fa-facebook.login__facebook_icon
            Facebookでログイン
        .login__form--google
          .login__form--google-button
            = image_tag('/links/google.svg', class: "login__google_icon")
            Googleでログイン
        .login__form--mercari-login
          = f.email_field :email, autofocus: true, class: "login__form--mercari-login-email", placeholder: "メールアドレス"

          = f.password_field :password, autocomplete: "off",class: "login__form--mercari-login-password",placeholder: "パスワード"
          .login__form--mercari-login-reCAPTCHA
            = image_tag('/links/reCAPTCHA.png', class: "login__form--mercari-login-reCAPTCHA-icon")
          = f.submit "ログイン", class: "login__form--mercari-login-submit"
        .login__form--forget
          = link_to 'パスワードをお忘れの方','',class: "login__form--forget-link"



  .login__fotter
    .login__fotter-buttons
      .login__fotter-button
        プライバシーポリシー
      .login__fotter-button
        メルカリ利用規約
      .login__fotter-button
        特定商取引に関する表記
    .login__fotter_icon
      = image_tag("/top_images/mercari_gray.svg")
    .login__fotter_copyright
      ©︎2019 Mercari